# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/SCPU/SCPU/SCPU.cache/wt [current_project]
set_property parent.project_path C:/SCPU/SCPU/SCPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/SCPU/SCPU/SCPU.srcs/sources_1/new/RegFile.v
  C:/SCPU/SCPU/SCPU.srcs/sources_1/new/PC.v
  C:/SCPU/SCPU/SCPU.srcs/sources_1/new/InsRom.v
  C:/SCPU/SCPU/SCPU.srcs/sources_1/new/Get_newPC.v
  C:/SCPU/SCPU/SCPU.srcs/sources_1/new/Extend.v
  C:/SCPU/SCPU/SCPU.srcs/sources_1/new/DataRam.v
  C:/SCPU/SCPU/SCPU.srcs/sources_1/new/ControlUnit.v
  C:/SCPU/SCPU/SCPU.srcs/sources_1/new/ALU.v
  C:/SCPU/SCPU/SCPU.srcs/sources_1/new/SCPU.v
  C:/SCPU/SCPU/SCPU.srcs/sources_1/new/7_SegLED.v
  C:/SCPU/SCPU/SCPU.srcs/sources_1/new/Xiaodou.v
  C:/SCPU/SCPU/SCPU.srcs/sources_1/new/counter4.v
  C:/SCPU/SCPU/SCPU.srcs/sources_1/new/clock_div.v
  C:/SCPU/SCPU/SCPU.srcs/sources_1/new/Display.v
}
read_xdc C:/SCPU/SCPU/SCPU.srcs/constrs_1/new/SCPU.xdc
set_property used_in_implementation false [get_files C:/SCPU/SCPU/SCPU.srcs/constrs_1/new/SCPU.xdc]

synth_design -top Display -part xc7a35tcpg236-1
write_checkpoint -noxdef Display.dcp
catch { report_utilization -file Display_utilization_synth.rpt -pb Display_utilization_synth.pb }
